const accounts = [
    {One:'1000',Two:'Business Checking',Three:'Checking'},
    {One:'1100',Two:'Money Market - Endowment',Three:'Money Market'},
    {One:'1106',Two:'Money Market - Oper/Temp Restr',Three:'Money Market'},
    {One:'1107',Two:'Money Market - Board Reserve/GALA Festival Designated',Three:'Money Market'},
    {One:'1200',Two:'Accounts Receivable',Three:'Accounts Receivable (A/R)'},
    {One:'1299',Two:'Doubtful accounts allowance',Three:'Accounts Receivable (A/R)'},
    {One:'1300',Two:'Pledges Receivable',Three:'Accounts Receivable (A/R)'},
    {One:'1305',Two:'Discounts - long-term pledges',Three:'Accounts Receivable (A/R)'},
    {One:'1310',Two:'Doubtful pledges allowance',Three:'Accounts Receivable (A/R)'},
    {One:'1320',Two:'Grants receivable',Three:'Accounts Receivable (A/R)'},
    {One:'1345',Two:'Discounts - long-term grants',Three:'Accounts Receivable (A/R)'},
    {One:'1400',Two:'Inventory - CDs, Videos',Three:'Inventory'},
    {One:'1500',Two:'Prepaid expenses',Three:'Prepaid Expenses'},
    {One:'1595',Two:'Deposits',Three:'Other Current Assets'},
    {One:'1705',Two:'Land - operating',Three:'Land'},
    {One:'1710',Two:'Buildings - operating',Three:'Buildings'},
    {One:'1720',Two:'Leasehold improvements',Three:'Leasehold Improvements'},
    {One:'1730',Two:'Furniture, fixtures & equipment',Three:'Furniture & Fixtures'},
    {One:'1735',Two:'Software',Three:'Other fixed assets'},
    {One:'1750',Two:'Vehicles',Three:'Vehicles'},
    {One:'1790',Two:'Accumulated depreciation',Three:'Accumulated Depreciation'},
    {One:'1800',Two:'Other long-term assets',Three:'Other Long-term Assets'},
    {One:'2000',Two:'Accounts payable',Three:'Accounts Payable (A/P)'},
    {One:'2050',Two:'Credit card',Three:'Credit Card'},
    {One:'2070',Two:'Consignment Sales Payable',Three:'Other Current Liabilities'},
    {One:'2071',Two:'Gifts Payable',Three:'Other Current Liabilities'},
    {One:'2075',Two:'Sales tax payable',Three:'Sales Tax Payable'},
    {One:'2080',Two:'Misc Payroll Liabilities',Three:'Other Current Liabilities'},
    {One:'2100',Two:'Accrued liabilities',Three:'Other Current Liabilities'},
    {One:'2200',Two:'Deferred revenue',Three:'Other Current Liabilities'},
    {One:'2310',Two:'Notes payable current - Board',Three:'Loan Payable'},
    {One:'2320',Two:'Line of credit payable',Three:'Line of Credit'},
    {One:'2330',Two:'Notes payable current - other',Three:'Loan Payable'},
    {One:'2400',Two:'Other current liabilities',Three:'Other Current Liabilities'},
    {One:'3000',Two:'Unrestricted net assets',Three:'Paid-In Capital or Surplus'},
    {One:'3100',Two:'Temporarily restricted net assets',Three:'Paid-In Capital or Surplus'},
    {One:'3200',Two:'Permanently restricted net assets',Three:'Paid-In Capital or Surplus'},
    {One:'40',Two:'Contributed support',Three:'Non-Profit Income'},
    {One:'4000',Two:'Contributed support:Individuals',Three:'Non-Profit Income'},
    {One:'4010',Two:'Contributed support:Uncollectible pledges - estim',Three:'Non-Profit Income'},
    {One:'4030',Two:'Contributed support:Corporate/foundations',Three:'Non-Profit Income'},
    {One:'4050',Two:'Contributed support:Gifts in kind - goods',Three:'Non-Profit Income'},
    {One:'4054',Two:'Contributed support:Donated prof services - GAAP',Three:'Non-Profit Income'},
    {One:'4055',Two:'Contributed support:Donated other services - non-GAAP',Three:'Non-Profit Income'},
    {One:'4070',Two:'Contributed support:Federal grants',Three:'Non-Profit Income'},
    {One:'4071',Two:'Contributed support:State grants',Three:'Non-Profit Income'},
    {One:'4072',Two:'Contributed support:Local government grants',Three:'Non-Profit Income'},
    {One:'41',Two:'Special events',Three:'Non-Profit Income'},
    {One:'4101',Two:'Special events:Dinner/auction',Three:'Non-Profit Income'},
    {One:'4105',Two:'Special events:2nd special event',Three:'Non-Profit Income'},
    {One:'4199',Two:'Special events:Other Events',Three:'Non-Profit Income'},
    {One:'42',Two:'Membership dues & fees',Three:'Non-Profit Income'},
    {One:'4200',Two:'Membership dues & fees:Dues',Three:'Non-Profit Income'},
    {One:'4210',Two:'Membership dues & fees:Retreat',Three:'Non-Profit Income'},
    {One:'4220',Two:'Membership dues & fees:Banquet',Three:'Non-Profit Income'},
    {One:'4229',Two:'Membership dues & fees:Other membership income',Three:'Non-Profit Income'},
    {One:'43',Two:'Ticket Sales',Three:'Non-Profit Income'},
    {One:'4305',Two:'Ticket Sales:Season',Three:'Non-Profit Income'},
    {One:'4310',Two:'Ticket Sales:Holiday concert',Three:'Non-Profit Income'},
    {One:'4320',Two:'Ticket Sales:Spring concert',Three:'Non-Profit Income'},
    {One:'4330',Two:'Ticket Sales:Pride concert',Three:'Non-Profit Income'},
    {One:'4340',Two:'Ticket Sales:Ensemble concert',Three:'Non-Profit Income'},
    {One:'44',Two:'Sales of Product',Three:'Sales of Product Income'},
    {One:'4410',Two:'Sales of Product:Compact discs',Three:'Sales of Product Income'},
    {One:'4411',Two:'Sales of Product:Digital Downloads',Three:'Sales of Product Income'},
    {One:'4415',Two:'Sales of Product:Videos',Three:'Sales of Product Income'},
    {One:'4420',Two:'Sales of Product:Clothing',Three:'Sales of Product Income'},
    {One:'4440',Two:'Sales of Product:Other sales',Three:'Sales of Product Income'},
    {One:'45',Two:'Other program income',Three:'Non-Profit Income'},
    {One:'4510',Two:'Other program income:Performance fees',Three:'Non-Profit Income'},
    {One:'4520',Two:'Other program income:Co-commission fees',Three:'Non-Profit Income'},
    {One:'4590',Two:'Other program income:Other program income',Three:'Non-Profit Income'},
    {One:'46',Two:'Investment income',Three:'Non-Profit Income'},
    {One:'4600',Two:'Investment income:Interest income',Three:'Non-Profit Income'},
    {One:'4610',Two:'Investment income:Dividend income',Three:'Non-Profit Income'},
    {One:'4620',Two:'Investment income:Unrealized gain/loss on investments',Three:'Non-Profit Income'},
    {One:'4630',Two:'Investment income:Gain/loss on stock sales',Three:'Non-Profit Income'},
    {One:'47',Two:'Miscellaneous Income',Three:'Non-Profit Income'},
    {One:'4700',Two:'Miscellaneous Income:Advertising - programs',Three:'Non-Profit Income'},
    {One:'4800',Two:'Miscellaneous Income:Miscellaneous revenue',Three:'Non-Profit Income'},
    {One:'5000',Two:'Cost of sales - inventory',Three:'Supplies & Materials - COGS'},
    {One:'5040',Two:'Mdse Commission - TMCH',Three:'Other Costs of Services - COS'},
    {One:'5050',Two:'Sales Taxes Paid',Three:'Other Costs of Services - COS'},
    {One:'5099',Two:'Cost of sales - inventory:Inventory write off obsolete',Three:'Supplies & Materials - COGS'},
    {One:'',Two:'Cost of Goods Sold',Three:'Supplies & Materials - COGS'},
    {One:'7000',Two:'Grant & contract expense',Three:'Office/General Administrative Expenses'},
    {One:'7010',Two:'Grant & contract expense:Contracts - program related',Three:'Office/General Administrative Expenses'},
    {One:'7020',Two:'Grant & contract expense:Grants to other organizations',Three:'Office/General Administrative Expenses'},
    {One:'7040',Two:'Grant & contract expense:Awards & grants - individuals',Three:'Office/General Administrative Expenses'},
    {One:'7050',Two:'Grant & contract expense:Specific assistance - individual',Three:'Office/General Administrative Expenses'},
    {One:'7060',Two:'Grant & contract expense:Benefits paid to or for members',Three:'Office/General Administrative Expenses'},
    {One:'7200',Two:'Salaries & related expenses',Three:'Payroll Expenses'},
    {One:'7210',Two:'Salaries & related expenses:Officers & directors salaries',Three:'Payroll Expenses'},
    {One:'7220',Two:'Salaries & related expenses:Salaries & wages - other',Three:'Payroll Expenses'},
    {One:'7230',Two:'Salaries & related expenses:Retirement plan - ER match',Three:'Payroll Expenses'},
    {One:'7240',Two:'Salaries & related expenses:Employee benefits - not pension',Three:'Payroll Expenses'},
    {One:'7240.01',Two:'Salaries & related expenses:Employee benefits - not pension:Medical/health insurance',Three:'Payroll Expenses'},
    {One:'7240.02',Two:'Salaries & related expenses:Employee benefits - not pension:Health Savings Account',Three:'Payroll Expenses'},
    {One:'7240.04',Two:'Salaries & related expenses:Employee benefits - not pension:Dental insurance',Three:'Payroll Expenses'},
    {One:'7240.08',Two:'Salaries & related expenses:Employee benefits - not pension:Life/AD&D insurance',Three:'Payroll Expenses'},
    {One:'7240.12',Two:'Salaries & related expenses:Employee benefits - not pension:Long term disability insurance',Three:'Payroll Expenses'},
    {One:'7240.16',Two:'Salaries & related expenses:Employee benefits - not pension:Short-term disability',Three:'Payroll Expenses'},
    {One:'7240.99',Two:'Salaries & related expenses:Employee benefits - not pension:Other employee benefits',Three:'Payroll Expenses'},
    {One:'7300',Two:'Salaries & related expenses:Payroll taxes',Three:'Payroll Expenses'},
    {One:'7305',Two:'Salaries & related expenses:Payroll taxes:FICA',Three:'Payroll Expenses'},
    {One:'7310',Two:'Salaries & related expenses:Payroll taxes:SUTA',Three:'Payroll Expenses'},
    {One:'7350',Two:'Salaries & related expenses:Workers compensation',Three:'Payroll Expenses'},
    {One:'7360',Two:'Salaries & related expenses:Staff development',Three:'Office/General Administrative Expenses'},
    {One:'7390',Two:'Salaries & related expenses:Staff recruiting',Three:'Advertising/Promotional'},
    {One:'7400',Two:'Other personnel expenses',Three:'Legal & Professional Fees'},
    {One:'7410',Two:'Other personnel expenses:Professional fundraising fees',Three:'Legal & Professional Fees'},
    {One:'7420',Two:'Other personnel expenses:Accounting fees',Three:'Legal & Professional Fees'},
    {One:'7430',Two:'Other personnel expenses:Legal fees',Three:'Legal & Professional Fees'},
    {One:'7435',Two:'Other personnel expenses:Consulting',Three:'Legal & Professional Fees'},
    {One:'7440',Two:'Other personnel expenses:Professional fees - other',Three:'Legal & Professional Fees'},
    {One:'7450',Two:'Other personnel expenses:Contracted services',Three:'Legal & Professional Fees'},
    {One:'7489',Two:'Other personnel expenses:Payroll processing',Three:'Legal & Professional Fees'},
    {One:'7490',Two:'Other personnel expenses:Donated pro services - GAAP',Three:'Legal & Professional Fees'},
    {One:'7495',Two:'Other personnel expenses:Donated other service - non-GAAP',Three:'Legal & Professional Fees'},
    {One:'7500',Two:'Concert production & related expenses',Three:'Office/General Administrative Expenses'},
    {One:'7510',Two:'Concert production & related expenses:Concert production',Three:'Office/General Administrative Expenses'},
    {One:'7515',Two:'Concert production & related expenses:Ticket Fees',Three:'Other Miscellaneous Service Cost'},
    {One:'7529',Two:'Concert production & related expenses:Concert production:Other concert production',Three:'Office/General Administrative Expenses'},
    {One:'7530',Two:'Concert production & related expenses:Contracted services',Three:'Office/General Administrative Expenses'},
    {One:'7540',Two:'Concert production & related expenses:Music',Three:'Office/General Administrative Expenses'},
    {One:'7545',Two:'Concert production & related expenses:Rental expense',Three:'Office/General Administrative Expenses'},
    {One:'7546',Two:'Concert production & related expenses:Rental expense:Concert hall',Three:'Rent or Lease of Buildings'},
    {One:'7547',Two:'Concert production & related expenses:Rental expense:Rehearsal',Three:'Rent or Lease of Buildings'},
    {One:'7550',Two:'Concert production & related expenses:Rehearsal tapes',Three:'Office/General Administrative Expenses'},
    {One:'7555',Two:'Concert production & related expenses:Archival recording - concert production',Three:'Office/General Administrative Expenses'},
    {One:'7560',Two:'Concert production & related expenses:Performance and music license fees',Three:'Office/General Administrative Expenses'},
    {One:'7570',Two:'Concert production & related expenses:Travel - guest artist',Three:'Travel'},
    {One:'7600',Two:'Membership',Three:'Office/General Administrative Expenses'},
    {One:'7605',Two:'Membership:Chorus retreat',Three:'Office/General Administrative Expenses'},
    {One:'7620',Two:'Membership:Wardrobe',Three:'Office/General Administrative Expenses'},
    {One:'7625',Two:'Membership:Survey Monkey',Three:'Office/General Administrative Expenses'},
    {One:'7630',Two:'Membership:Leadership Consulting/Training',Three:'Office/General Administrative Expenses'},
    {One:'7660',Two:'Membership:Scholarships',Three:'Travel'},
    {One:'7665',Two:'Membership:Receptions/other events - membership',Three:'Office/General Administrative Expenses'},
    {One:'7670',Two:'Membership:Advertising - Member recruiting',Three:'Advertising/Promotional'},
    {One:'7675',Two:'Membership:Member Care',Three:'Office/General Administrative Expenses'},
    {One:'7700',Two:'Festival/Outreach Expenses',Three:'Travel'},
    {One:'7705',Two:'Festival/Outreach Expenses:Festival registration',Three:'Travel'},
    {One:'7710',Two:'Festival/Outreach Expenses:Festival/tour transportation',Three:'Travel'},
    {One:'7715',Two:'Festival/Outreach Expenses:Festival/tour lodging',Three:'Travel'},
    {One:'7720',Two:'Festival/Outreach Expenses:Outreach travel lodging',Three:'Travel'},
    {One:'7725',Two:'Festival/Outreach Expenses:Outreach travel - transportation',Three:'Travel'},
    {One:'7730',Two:'Festival/Outreach Expenses:Outreach travel - other',Three:'Travel'},
    {One:'7800',Two:'Event Costs',Three:'Office/General Administrative Expenses'},
    {One:'7805',Two:'Event Costs:Dinner/auction',Three:'Office/General Administrative Expenses'},
    {One:'7806',Two:'Event Costs:2nd special event',Three:'Other Miscellaneous Service Cost'},
    {One:'7899',Two:'Event Costs:Miscellaneous events',Three:'Office/General Administrative Expenses'},
    {One:'8100',Two:'Office & related expenses',Three:'Office/General Administrative Expenses'},
    {One:'8101',Two:'Office & related expenses:Supplies & building maintenance',Three:'Office/General Administrative Expenses'},
    {One:'8130',Two:'Office & related expenses:Telephone/communications',Three:'Office/General Administrative Expenses'},
    {One:'8140',Two:'Office & related expenses:Postage, shipping, delivery',Three:'Office/General Administrative Expenses'},
    {One:'8145',Two:'Office & related expenses:Other shipping and handling',Three:'Office/General Administrative Expenses'},
    {One:'8150',Two:'Office & related expenses:Mailing services',Three:'Office/General Administrative Expenses'},
    {One:'8161',Two:'Office & related expenses:Equipment-related expenses:Equipment repair/maintenance',Three:'Repair & Maintenance'},
    {One:'8162',Two:'Office & related expenses:Equipment-related expenses:Computer system repair/maintenance',Three:'Office/General Administrative Expenses'},
    {One:'8166',Two:'Office & related expenses:Equipment-related expenses:Equipment lease/rental',Three:'Equipment Rental'},
    {One:'8168',Two:'Office & related expenses:Equipment-related expenses:Computer lease/rental',Three:'Equipment Rental'},
    {One:'8169',Two:'Office & related expenses:Equipment-related expenses:Other equipment expense',Three:'Office/General Administrative Expenses'},
    {One:'8180',Two:'Office & related expenses:In-house publications',Three:'Office/General Administrative Expenses'},
    {One:'8185',Two:'Office & related expenses:Books, subscriptions, reference',Three:'Office/General Administrative Expenses'},
    {One:'8190',Two:'Printing & copying',Three:'Office/General Administrative Expenses'},
    {One:'8191',Two:'Printing & copying:Printing',Three:'Office/General Administrative Expenses'},
    {One:'8193',Two:'Printing & copying:Programs',Three:'Office/General Administrative Expenses'},
    {One:'8195',Two:'Printing & copying:Photocopies',Three:'Office/General Administrative Expenses'},
    {One:'8197',Two:'Printing & copying:Other print & photo expense',Three:'Office/General Administrative Expenses'},
    {One:'8200',Two:'Occupancy',Three:'Rent or Lease of Buildings'},
    {One:'8210',Two:'Occupancy:Rent, parking, other occupancy',Three:'Rent or Lease of Buildings'},
    {One:'8300',Two:'Travel & meetings expenses',Three:'Travel'},
    {One:'8310',Two:'Travel & meetings expenses:Travel',Three:'Travel'},
    {One:'8311',Two:'Travel & meetings expenses:Travel:Local',Three:'Travel'},
    {One:'8312',Two:'Travel & meetings expenses:Travel:Out-of-town',Three:'Travel'},
    {One:'8320',Two:'Travel & meetings expenses:Meeting expenses',Three:'Travel'},
    {One:'8321',Two:'Travel & meetings expenses:Meeting expenses:Board',Three:'Travel'},
    {One:'8322',Two:'Travel & meetings expenses:Meeting expenses:Committee',Three:'Travel'},
    {One:'8323',Two:'Travel & meetings expenses:Meeting expenses:Staff',Three:'Travel'},
    {One:'8324',Two:'Travel & meetings expenses:Meeting expenses:Business meetings',Three:'Office/General Administrative Expenses'},
    {One:'8400',Two:'Advertising & promotion',Three:'Advertising/Promotional'},
    {One:'8410',Two:'Advertising & promotion:Advertising expenses',Three:'Advertising/Promotional'},
    {One:'8430',Two:'Advertising & promotion:Promotional expenses',Three:'Advertising/Promotional'},
    {One:'8450',Two:'Development Expense',Three:'Promotional Meals'},
    {One:'8500',Two:'Other administrative expenses',Three:'Office/General Administrative Expenses'},
    {One:'8501',Two:'Other administrative expenses:Interest, credit card & bank fees',Three:'Office/General Administrative Expenses'},
    {One:'8520',Two:'Other administrative expenses:Insurance - non-employee',Three:'Insurance'},
    {One:'8530',Two:'Other administrative expenses:Dues & Licenses',Three:'Office/General Administrative Expenses'},
    {One:'8560',Two:'Other administrative expenses:Mail list rental',Three:'Office/General Administrative Expenses'},
    {One:'8590',Two:'Other administrative expenses:Other expenses',Three:'Office/General Administrative Expenses'},
    {One:'8595',Two:'Other administrative expenses:Contingency provisions',Three:'Office/General Administrative Expenses'},
    {One:'8600',Two:'Other administrative expenses:General business expenses',Three:'Office/General Administrative Expenses'},
    {One:'8610',Two:'Other administrative expenses:General business expenses:Bad debt expense',Three:'Office/General Administrative Expenses'},
    {One:'8630',Two:'Other administrative expenses:General business expenses:UBI Taxes',Three:'Office/General Administrative Expenses'},
    {One:'8650',Two:'Other administrative expenses:General business expenses:Taxes - other',Three:'Office/General Administrative Expenses'},
    {One:'8660',Two:'Other administrative expenses:General business expenses:Fines, penalties, judgements',Three:'Office/General Administrative Expenses'},
    {One:'8670',Two:'Other administrative expenses:General business expenses:Organizational (corp) expenses',Three:'Office/General Administrative Expenses'},
    {One:'8699',Two:'Other administrative expenses:General business expenses:Depreciation Expense',Three:'Office/General Administrative Expenses'}
];

export default accounts;